/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formation.graph;

import formation.DAO.FormateurDAO;
import formation.DAO.InfosDAO;
import formation.DAO.SessionCoursDAO;
import formation.metier.Formateur;
import formation.metier.Infos;
import formation.metier.SessionCours;
import java.sql.SQLException;
import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author BARCA
 */
public class CreationInfos extends javax.swing.JPanel {

    /**
     * Creates new form CreationInfos
     */
     InfosDAO infosDAO=null;
     FormateurDAO formateurDAO = null;
     SessionCoursDAO sessionCoursDAO = null;
     
      List<Formateur> f;
      List<SessionCours> sess;

      DefaultComboBoxModel dc = new DefaultComboBoxModel();

      DefaultComboBoxModel dc2 = new DefaultComboBoxModel();
      
      public void comboFormateur() {
       
        try {
            f = formateurDAO.comboFormateur();
            if (comboIdform != null) {
                comboIdform.removeAllItems();
            }
            Iterator<Formateur> itform = f.iterator();
            while (itform.hasNext()) {
                Formateur f2 = itform.next();
                dc.addElement(f2.toStringComboFormateur());
            }
            
            comboIdform.setModel(dc);

        } catch (SQLException e) {
            System.out.println("Exception" + e);
        }


    }

    public void comboSessioncours() {
     
     
     try {
            sess = sessionCoursDAO.comboSessioncours();
            if (comboIdsessioncours != null) {
                comboIdsessioncours.removeAllItems();
            }
            Iterator<SessionCours> itseccs = sess.iterator();
            while (itseccs.hasNext()) {
                SessionCours sco = itseccs.next();
                dc2.addElement(sco.toStringComboSessionCours());
            }
            
            comboIdsessioncours.setModel(dc2);

        } catch (SQLException e) {
            System.out.println("Exception" + e);
        }

    }

    public CreationInfos() {
        initComponents();
    }
    public void setInfosDAO(InfosDAO infosDAO){
        this.infosDAO=infosDAO;
    }
    public void setFormateurDAO(FormateurDAO formateurDAO) {
        this.formateurDAO = formateurDAO;
    }
    
    public void setSessionCoursDAO(SessionCoursDAO sessionCoursDAO) {
        this.sessionCoursDAO = sessionCoursDAO;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdinfos = new javax.swing.JTextField();
        txtNb = new javax.swing.JTextField();
        btCreation = new javax.swing.JButton();
        comboIdform = new javax.swing.JComboBox<>();
        comboIdsessioncours = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Creation infos");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("idInfos");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 255));
        jLabel3.setText("nb");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 255));
        jLabel4.setText("idform");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 255));
        jLabel5.setText("idsessioncours");

        txtIdinfos.setEditable(false);

        btCreation.setText("création");
        btCreation.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), new java.awt.Color(0, 153, 255), new java.awt.Color(0, 153, 255), new java.awt.Color(0, 153, 255)));
        btCreation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreationActionPerformed(evt);
            }
        });

        comboIdform.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboIdform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboIdformActionPerformed(evt);
            }
        });

        comboIdsessioncours.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboIdsessioncours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboIdsessioncoursActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(161, 161, 161)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboIdsessioncours, 0, 150, Short.MAX_VALUE)
                            .addComponent(comboIdform, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNb)
                            .addComponent(txtIdinfos)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(btCreation, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(283, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdinfos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(comboIdform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboIdsessioncours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(btCreation)
                .addGap(127, 127, 127))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btCreationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreationActionPerformed
        // TODO add your handling code here:
        try{       
            int nb=Integer.parseInt(txtNb.getText());
            int pos = comboIdform.getSelectedIndex();
            Formateur f1 = f.get(pos);
            int pos1 = comboIdsessioncours.getSelectedIndex();
            SessionCours sess1 = sess.get(pos1);
            Infos i = new Infos(0,nb,f1.getIdform(),sess1.getIdsesscours());
            i=infosDAO.create(i);
            txtIdinfos.setText(""+i.getIdinfos());
            JOptionPane.showMessageDialog(this,"infos créé","succès",JOptionPane.INFORMATION_MESSAGE);
            
         }
     catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage(),"ERREUR",JOptionPane.ERROR_MESSAGE);
     }
        
    }//GEN-LAST:event_btCreationActionPerformed

    private void comboIdsessioncoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboIdsessioncoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboIdsessioncoursActionPerformed

    private void comboIdformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboIdformActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboIdformActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCreation;
    private javax.swing.JComboBox<String> comboIdform;
    private javax.swing.JComboBox<String> comboIdsessioncours;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtIdinfos;
    private javax.swing.JTextField txtNb;
    // End of variables declaration//GEN-END:variables
}
