/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formation.graph;

import formation.DAO.LocalDAO;
import java.awt.CardLayout;
import java.sql.Connection;
import javax.swing.JOptionPane;
import myconnections.DBConnection;
/**
 *
 * @author BARCA
 */
public class GestionLocal extends javax.swing.JFrame {

    /**
     * Creates new form GestionLocal
     */
    CardLayout cardl;
    public GestionLocal() {
        initComponents();
        cardl=(CardLayout)this.getContentPane().getLayout();
         Connection dbConnect = DBConnection.getConnection();
   
        if (dbConnect == null) {
            System.out.println("connection invalide");
            JOptionPane.showMessageDialog(this,"connexion invalide","ERREUR",JOptionPane.ERROR_MESSAGE);
        }
         
 
    LocalDAO localDAO = new LocalDAO();
    localDAO.setConnection(dbConnect);
    creationLocal1.setLocalDAO(localDAO);
    rechLocalDescription1.setLocalDAO(localDAO);
    rechLocalSigle1.setLocalDAO(localDAO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        creationLocal1 = new formation.graph.CreationLocal();
        rechLocalDescription1 = new formation.graph.RechLocalDescription();
        rechLocalSigle1 = new formation.graph.RechLocalSigle();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuLocal = new javax.swing.JMenu();
        itemCreat = new javax.swing.JMenuItem();
        itemRechS = new javax.swing.JMenuItem();
        itemRechDesc = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(creationLocal1, "cardCreation");
        getContentPane().add(rechLocalDescription1, "cardRechDesc");
        getContentPane().add(rechLocalSigle1, "cardRechSigle");

        MenuLocal.setText("Local");

        itemCreat.setText("créer");
        itemCreat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCreatActionPerformed(evt);
            }
        });
        MenuLocal.add(itemCreat);

        itemRechS.setText("recherche par sigle");
        itemRechS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRechSActionPerformed(evt);
            }
        });
        MenuLocal.add(itemRechS);

        itemRechDesc.setText("recherche par description");
        itemRechDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRechDescActionPerformed(evt);
            }
        });
        MenuLocal.add(itemRechDesc);

        jMenuBar1.add(MenuLocal);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCreatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCreatActionPerformed
        // TODO add your handling code here:
        cardl.show(this.getContentPane(), "cardCreation");
    }//GEN-LAST:event_itemCreatActionPerformed

    private void itemRechSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRechSActionPerformed
        // TODO add your handling code here:
        cardl.show(this.getContentPane(), "cardRechSigle");
    }//GEN-LAST:event_itemRechSActionPerformed

    private void itemRechDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRechDescActionPerformed
        // TODO add your handling code here:
        cardl.show(this.getContentPane(), "cardRechDesc");
    }//GEN-LAST:event_itemRechDescActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionLocal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuLocal;
    private formation.graph.CreationLocal creationLocal1;
    private javax.swing.JMenuItem itemCreat;
    private javax.swing.JMenuItem itemRechDesc;
    private javax.swing.JMenuItem itemRechS;
    private javax.swing.JMenuBar jMenuBar1;
    private formation.graph.RechLocalDescription rechLocalDescription1;
    private formation.graph.RechLocalSigle rechLocalSigle1;
    // End of variables declaration//GEN-END:variables
}
