/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formation.graph;

import formation.DAO.LocalDAO;
import formation.metier.Local;
import javax.swing.JOptionPane;

/**
 *
 * @author BARCA
 */
public class RechLocalSigle extends javax.swing.JPanel {

    /**
     * Creates new form RechLocalSigle
     */
    LocalDAO localDAO=null;
    Local loc=null;
    public RechLocalSigle() {
        initComponents();
        
    }
    public void setLocalDAO(LocalDAO localDAO){
        this.localDAO=localDAO;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSigle = new javax.swing.JLabel();
        labelPlaces = new javax.swing.JLabel();
        labelDescription = new javax.swing.JLabel();
        txtPlaces = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        btRecherche = new javax.swing.JButton();
        btMaj = new javax.swing.JButton();
        btEffacer = new javax.swing.JButton();
        labelIdlocal = new javax.swing.JLabel();
        txtIdlocal = new javax.swing.JTextField();
        txtSigle = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        labelSigle.setBackground(new java.awt.Color(0, 153, 255));
        labelSigle.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelSigle.setForeground(new java.awt.Color(0, 153, 255));
        labelSigle.setText("Sigle");

        labelPlaces.setBackground(new java.awt.Color(0, 153, 255));
        labelPlaces.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelPlaces.setForeground(new java.awt.Color(0, 153, 255));
        labelPlaces.setText("Places");

        labelDescription.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelDescription.setForeground(new java.awt.Color(0, 153, 255));
        labelDescription.setText("Description");

        txtPlaces.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtDescription.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        btRecherche.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btRecherche.setText("rechercher");
        btRecherche.setActionCommand("rechercher");
        btRecherche.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), new java.awt.Color(0, 153, 255), new java.awt.Color(0, 153, 255), new java.awt.Color(0, 153, 255)));
        btRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRechercheActionPerformed(evt);
            }
        });

        btMaj.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btMaj.setText("maj");
        btMaj.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), new java.awt.Color(0, 153, 255), new java.awt.Color(0, 153, 255), new java.awt.Color(0, 153, 255)));
        btMaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMajActionPerformed(evt);
            }
        });

        btEffacer.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btEffacer.setText("supprimer");
        btEffacer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), new java.awt.Color(0, 153, 255), new java.awt.Color(0, 153, 255), new java.awt.Color(0, 153, 255)));
        btEffacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEffacerActionPerformed(evt);
            }
        });

        labelIdlocal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelIdlocal.setForeground(new java.awt.Color(255, 255, 255));
        labelIdlocal.setText("Idlocal");

        txtIdlocal.setEditable(false);
        txtIdlocal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtSigle.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Recherche d'un local selon son sigle");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(168, 168, 168)
                        .addComponent(btMaj, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(btEffacer, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelSigle)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSigle, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelPlaces)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPlaces, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelDescription)
                                    .addGap(144, 144, 144)
                                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelIdlocal)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtIdlocal, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSigle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSigle))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdlocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIdlocal))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlaces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPlaces))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDescription)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRecherche)
                    .addComponent(btMaj)
                    .addComponent(btEffacer))
                .addGap(127, 127, 127))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRechercheActionPerformed
        // TODO add your handling code here:
        try{
             String sigle= txtSigle.getText();
             loc=localDAO.readSigle(sigle);
             txtIdlocal.setText(""+loc.getIdlocal());
             txtPlaces.setText(""+loc.getPlaces());
             txtDescription.setText(loc.getDescription());
             JOptionPane.showMessageDialog(this,"local trouvé","succès",JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage(),"ERREUR",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btRechercheActionPerformed
    }
    private void btMajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMajActionPerformed
        // TODO add your handling code here:
        try{  
       String sigle=txtSigle.getText();
       int idlocal=Integer.parseInt(txtIdlocal.getText());
       int places=Integer.parseInt(txtPlaces.getText());
       String description=txtDescription.getText();
       Local loc = new Local(idlocal,sigle,places,description);
       localDAO.update(loc);
       JOptionPane.showMessageDialog(this,"local mis à jour","succès",JOptionPane.INFORMATION_MESSAGE);
       
     }
     catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage(),"ERREUR",JOptionPane.ERROR_MESSAGE);
     }
        
    }//GEN-LAST:event_btMajActionPerformed

    private void btEffacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEffacerActionPerformed
        // TODO add your handling code here:
        try{
             String sigle=txtSigle.getText();
             localDAO.delete(loc);
             txtIdlocal.setText("");
             txtPlaces.setText("");
             txtDescription.setText("");
             
             JOptionPane.showMessageDialog(this,"local effacé","succès",JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage(),"ERREUR",JOptionPane.ERROR_MESSAGE);
     }
    }//GEN-LAST:event_btEffacerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEffacer;
    private javax.swing.JButton btMaj;
    private javax.swing.JButton btRecherche;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelDescription;
    private javax.swing.JLabel labelIdlocal;
    private javax.swing.JLabel labelPlaces;
    private javax.swing.JLabel labelSigle;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtIdlocal;
    private javax.swing.JTextField txtPlaces;
    private javax.swing.JTextField txtSigle;
    // End of variables declaration//GEN-END:variables
}
