/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formation.graph;

import formation.DAO.LocalDAO;
import formation.metier.Local;
import javax.swing.JOptionPane;

/**
 *
 * @author BARCA
 */
public class RechLocalSigle extends javax.swing.JPanel {

    /**
     * Creates new form RechLocalSigle
     */
    LocalDAO localDAO=null;
    Local loc=null;
    public RechLocalSigle() {
        initComponents();
        
    }
    public void setLocalDAO(LocalDAO localDAO){
        this.localDAO=localDAO;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSigle = new javax.swing.JLabel();
        labelPlaces = new javax.swing.JLabel();
        labelDescription = new javax.swing.JLabel();
        txtPlaces = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        btRecherche = new javax.swing.JButton();
        btMaj = new javax.swing.JButton();
        btEffacer = new javax.swing.JButton();
        labelIdlocal = new javax.swing.JLabel();
        txtIdlocal = new javax.swing.JTextField();
        txtSigle = new javax.swing.JTextField();

        setBackground(new java.awt.Color(51, 204, 255));

        labelSigle.setText("Sigle");

        labelPlaces.setText("Places");

        labelDescription.setText("Description");

        btRecherche.setText("Rechercher");
        btRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRechercheActionPerformed(evt);
            }
        });

        btMaj.setText("Maj");
        btMaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMajActionPerformed(evt);
            }
        });

        btEffacer.setText("Effacer");
        btEffacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEffacerActionPerformed(evt);
            }
        });

        labelIdlocal.setText("Idlocal");

        txtIdlocal.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btMaj, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btEffacer, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSigle)
                            .addComponent(labelIdlocal))
                        .addGap(174, 174, 174)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdlocal)
                            .addComponent(txtSigle, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDescription)
                            .addComponent(labelPlaces))
                        .addGap(152, 152, 152)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPlaces, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSigle)
                    .addComponent(txtSigle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdlocal)
                    .addComponent(txtIdlocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPlaces)
                    .addComponent(txtPlaces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDescription)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRecherche)
                    .addComponent(btMaj)
                    .addComponent(btEffacer))
                .addContainerGap(104, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRechercheActionPerformed
        // TODO add your handling code here:
        try{
             String sigle= txtSigle.getText();
             loc=localDAO.readSigle(sigle);
             txtIdlocal.setText(""+loc.getIdlocal());
             txtPlaces.setText(""+loc.getPlaces());
             txtDescription.setText(loc.getDescription());
             JOptionPane.showMessageDialog(this,"local trouvé","succès",JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage(),"ERREUR",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btRechercheActionPerformed
    }
    private void btMajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMajActionPerformed
        // TODO add your handling code here:
        try{  
       String sigle=txtSigle.getText();
       int idlocal=Integer.parseInt(txtIdlocal.getText());
       int places=Integer.parseInt(txtPlaces.getText());
       String description=txtDescription.getText();
       Local loc = new Local(idlocal,sigle,places,description);
       localDAO.update(loc);
       JOptionPane.showMessageDialog(this,"local mis à jour","succès",JOptionPane.INFORMATION_MESSAGE);
       
     }
     catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage(),"ERREUR",JOptionPane.ERROR_MESSAGE);
     }
        
    }//GEN-LAST:event_btMajActionPerformed

    private void btEffacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEffacerActionPerformed
        // TODO add your handling code here:
        try{
             String sigle=txtSigle.getText();
             localDAO.delete(loc);
             txtIdlocal.setText("");
             txtPlaces.setText("");
             txtDescription.setText("");
             
             JOptionPane.showMessageDialog(this,"local effacé","succès",JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage(),"ERREUR",JOptionPane.ERROR_MESSAGE);
     }
    }//GEN-LAST:event_btEffacerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEffacer;
    private javax.swing.JButton btMaj;
    private javax.swing.JButton btRecherche;
    private javax.swing.JLabel labelDescription;
    private javax.swing.JLabel labelIdlocal;
    private javax.swing.JLabel labelPlaces;
    private javax.swing.JLabel labelSigle;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtIdlocal;
    private javax.swing.JTextField txtPlaces;
    private javax.swing.JTextField txtSigle;
    // End of variables declaration//GEN-END:variables
}
